
import './components/Header';
import './components/Footer';
import './pages/Home';
import './pages/OurStory';
import './pages/Collections';
import './pages/Journal';
import './pages/Contact';
import './pages/Login';
import './pages/ProductDetail';
import './pages/ArticleView';
// import './pages/admin/AdminLogin';
// import './pages/admin/AdminLayout';
// import './pages/admin/Dashboard';
// import './pages/admin/ProductManager';
// import './pages/admin/ProductEditor';
// import './pages/admin/SiteSettings';
// import './pages/admin/ThemeSettings';
// import './pages/admin/PageManager';
// import './pages/admin/SectionEditor';
// import './pages/admin/NavigationManager';
// import './pages/admin/ContentManager';
// import './pages/admin/ContentEditor';
// import './components/ProtectedRoute';
// import './pages/PrivacyPolicy';
// import './pages/TermsConditions';
import './components/MaintenanceGuard';
// import './components/HeadManager';

console.log('Test imports completed');
