-- 1. Reset RLS Policies to ensure clean slate
alter table products enable row level security;

-- Drop existing policies to avoid conflicts
drop policy if exists "Enable read access for all users" on products;
drop policy if exists "Enable insert for authenticated users only" on products;
drop policy if exists "Enable update for authenticated users only" on products;
drop policy if exists "Enable delete for authenticated users only" on products;

-- 2. Re-create Policies (Strict)

-- Allow PUBLIC read access (so website visitors can see products)
create policy "Enable read access for all users"
on products for select
using (true);

-- Allow AUTHENTICATED users (Admins) to Insert
create policy "Enable insert for authenticated users only"
on products for insert
with check (auth.role() = 'authenticated');

-- Allow AUTHENTICATED users (Admins) to Update
create policy "Enable update for authenticated users only"
on products for update
using (auth.role() = 'authenticated');

-- Allow AUTHENTICATED users (Admins) to Delete
create policy "Enable delete for authenticated users only"
on products for delete
using (auth.role() = 'authenticated');

-- 3. Verify Table Structure (Idempotent changes)
-- This ensures columns exist. If they already exist, this does nothing (or errors harmlessly in some SQL flavors, but 'add column if not exists' is safer manually)
-- Since Supabase SQL editor doesn't support 'if not exists' for columns easily in standard postgres without a do block, 
-- WE WILL ASSUME simple create if table missing:

create table if not exists products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  category text,
  image text,
  gallery text[],
  color text,
  description text,
  details text[]
);
